-- auto Generated on 2022-09-10
-- DROP TABLE IF EXISTS me;
CREATE TABLE me(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '主键',
	surname VARCHAR (50) NOT NULL DEFAULT '' COMMENT '姓',
	given_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '名',
	name_ek VARCHAR (50) NOT NULL DEFAULT '' COMMENT '英文名',
	info LONGTEXT NOT NULL COMMENT '附加信息',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'me';
