-- auto Generated on 2022-09-10
-- DROP TABLE IF EXISTS tag;
CREATE TABLE tag(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` VARCHAR (255) NOT NULL DEFAULT '' COMMENT '标签名',
	mark VARCHAR (255) NOT NULL DEFAULT '' COMMENT '标签的标记',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'tag';
