-- auto Generated on 2022-09-10
-- DROP TABLE IF EXISTS visitor;
CREATE TABLE visitor(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '主键',
	uuid VARCHAR (255) NOT NULL DEFAULT '' COMMENT '用户标识',
	ip VARCHAR (255) NOT NULL DEFAULT '' COMMENT 'ip',
	ip_address VARCHAR (255) NOT NULL DEFAULT '' COMMENT 'ip地址',
	os VARCHAR (255) NOT NULL DEFAULT '' COMMENT 'Operation System',
	last_visit DATETIME NOT NULL DEFAULT now() COMMENT '最后访问时间',
	create_t_ime DATETIME NOT NULL DEFAULT now() COMMENT '创建时间',
	browser VARCHAR (255) NOT NULL DEFAULT '' COMMENT '浏览器',
	visit_count BIGINT (15) NOT NULL DEFAULT -1 COMMENT '浏览次数',
	user_agent VARCHAR (2000) NOT NULL DEFAULT '' COMMENT '用户代理',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'visitor';
